/**
 * @author paulamh
 */
package bsc;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class BSC extends javax.swing.JFrame {
    private final Icon icono = new ImageIcon(getClass().getResource("/images/bsc_100x100.png"));
    private final Icon iconoError = new ImageIcon(getClass().getResource("/images/error_bsc.png"));
    private final Icon iconoWarning = new ImageIcon(getClass().getResource("/images/warning_bsc.png"));

    public Icon getIcono() {
        return icono;
    }

    public Icon getIconoError() {
        return iconoError;
    }

    public Icon getIconoWarning() {
        return iconoWarning;
    }
    
    Equipo equipo = new Equipo(0, null, 0);
    Resultados resultados = new Resultados(0, 0, 0, 0, 0, 0, 0);
    static DefaultTableModel dtm = new DefaultTableModel();
        
        
    public BSC() {
        initComponents();
        setTitle("Brawl Stars Championship 2023");
        setSize(1920, 1080);
        equipo.importaDatosEquipo();
        resultados.importaDatosResultados();
        tabla.setModel(dtm);
        setIconImage(new ImageIcon(getClass().getResource("/images/bsc_100x100.png")).getImage());  
    }
    
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/bsc_100x100.png"));
        return retValue;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button1 = new java.awt.Button();
        jPanel2 = new javax.swing.JPanel();
        introduceResultados = new javax.swing.JButton();
        mostrarResultados = new javax.swing.JButton();
        eliminarResultados = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        crearEquipo = new javax.swing.JButton();
        mostrarEquipos = new javax.swing.JButton();
        modificarEquipo = new javax.swing.JButton();
        eliminarEquipo = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        textoEquipo = new javax.swing.JTextField();
        buscarEquipo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        imagen = new javax.swing.JLabel();
        limpiar = new javax.swing.JToggleButton();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        verFechas = new javax.swing.JButton();
        clasificadosLCQ = new javax.swing.JToggleButton();
        verResultadosTotales = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        salir = new javax.swing.JButton();
        mostrarEquiposClasificadosWorlds1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        Archivo = new javax.swing.JMenu();
        limpiarTab = new javax.swing.JMenuItem();
        salirPrograma = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        crearEq = new javax.swing.JMenuItem();
        mostrarEq = new javax.swing.JMenuItem();
        modificarEq = new javax.swing.JMenuItem();
        eliminarEq = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        introducirRes = new javax.swing.JMenuItem();
        verRes = new javax.swing.JMenuItem();
        eliminarRes = new javax.swing.JMenuItem();
        vResultadosTot = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        verEqClas = new javax.swing.JMenuItem();
        clasfLCQ = new javax.swing.JMenuItem();
        mostrarFec = new javax.swing.JMenuItem();

        button1.setLabel("button1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        introduceResultados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-guardar-30.png"))); // NOI18N
        introduceResultados.setText("Añadir resultados");
        introduceResultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                introduceResultadosActionPerformed(evt);
            }
        });
        jPanel2.add(introduceResultados);

        mostrarResultados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-ver-30.png"))); // NOI18N
        mostrarResultados.setText("Ver resultados");
        mostrarResultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarResultadosActionPerformed(evt);
            }
        });
        jPanel2.add(mostrarResultados);

        eliminarResultados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-papelera-30.png"))); // NOI18N
        eliminarResultados.setText("Borrar resultados");
        eliminarResultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarResultadosActionPerformed(evt);
            }
        });
        jPanel2.add(eliminarResultados);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 330, 510, 40));

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        crearEquipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-añadir-usuario-masculino-30.png"))); // NOI18N
        crearEquipo.setText("Crear equipo");
        crearEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearEquipoActionPerformed(evt);
            }
        });
        jPanel1.add(crearEquipo);

        mostrarEquipos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-ojo-30.png"))); // NOI18N
        mostrarEquipos.setText("Mostrar equipos");
        mostrarEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarEquiposActionPerformed(evt);
            }
        });
        jPanel1.add(mostrarEquipos);

        modificarEquipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-editar-30.png"))); // NOI18N
        modificarEquipo.setText("Modificar equipo");
        modificarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarEquipoActionPerformed(evt);
            }
        });
        jPanel1.add(modificarEquipo);

        eliminarEquipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-borrar-30.png"))); // NOI18N
        eliminarEquipo.setText("Eliminar equipo");
        eliminarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarEquipoActionPerformed(evt);
            }
        });
        jPanel1.add(eliminarEquipo);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 660, 40));

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1620, 60, 70, 30));

        textoEquipo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(textoEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 180, 40));

        buscarEquipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-lupa-30.png"))); // NOI18N
        buscarEquipo.setText("Buscar equipo");
        buscarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarEquipoActionPerformed(evt);
            }
        });
        getContentPane().add(buscarEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 160, -1));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id", "Nombre de equipo", "Región", "Puntos"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 1240, 420));

        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bsc_200x200.png"))); // NOI18N
        getContentPane().add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 60, 210, 220));

        limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-limpio-30.png"))); // NOI18N
        limpiar.setText("Limpiar tabla");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });
        getContentPane().add(limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 830, 170, -1));

        label1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label1.setText("Gestión de equipos");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 180, -1));

        label2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label2.setText("Gestión de resultados");
        getContentPane().add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 290, 210, -1));

        verFechas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-calendario-30.png"))); // NOI18N
        verFechas.setText("Mostrar fechas");
        verFechas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verFechasActionPerformed(evt);
            }
        });
        getContentPane().add(verFechas, new org.netbeans.lib.awtextra.AbsoluteConstraints(1510, 510, 300, -1));

        clasificadosLCQ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-planeta-tierra-30.png"))); // NOI18N
        clasificadosLCQ.setText("Ver equipos clasificados LCQ");
        clasificadosLCQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clasificadosLCQActionPerformed(evt);
            }
        });
        getContentPane().add(clasificadosLCQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(1510, 450, 300, 40));

        verResultadosTotales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-boleta-de-calificaciones-30.png"))); // NOI18N
        verResultadosTotales.setText("Ver resultados totales");
        verResultadosTotales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verResultadosTotalesActionPerformed(evt);
            }
        });
        getContentPane().add(verResultadosTotales, new org.netbeans.lib.awtextra.AbsoluteConstraints(1510, 330, 300, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("BSC Championship");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1570, 280, 180, 40));

        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-salida-30.png"))); // NOI18N
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1690, 50, 110, 50));

        mostrarEquiposClasificadosWorlds1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-trofeo-30.png"))); // NOI18N
        mostrarEquiposClasificadosWorlds1.setText("Ver equipos clasificados Worlds");
        mostrarEquiposClasificadosWorlds1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarEquiposClasificadosWorlds1ActionPerformed(evt);
            }
        });
        getContentPane().add(mostrarEquiposClasificadosWorlds1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1510, 390, 300, 40));

        Archivo.setText("Archivo");

        limpiarTab.setText("Limpiar tabla");
        limpiarTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarTabActionPerformed(evt);
            }
        });
        Archivo.add(limpiarTab);

        salirPrograma.setText("Salir");
        salirPrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirProgramaActionPerformed(evt);
            }
        });
        Archivo.add(salirPrograma);

        jMenuBar1.add(Archivo);

        jMenu2.setText("Equipos");

        crearEq.setText("Crear nuevo equipo");
        crearEq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearEqActionPerformed(evt);
            }
        });
        jMenu2.add(crearEq);

        mostrarEq.setText("Mostrar equipos");
        mostrarEq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarEqActionPerformed(evt);
            }
        });
        jMenu2.add(mostrarEq);

        modificarEq.setText("Modificar equipo");
        modificarEq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarEqActionPerformed(evt);
            }
        });
        jMenu2.add(modificarEq);

        eliminarEq.setText("Eliminar equipo");
        eliminarEq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarEqActionPerformed(evt);
            }
        });
        jMenu2.add(eliminarEq);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Resultados");

        introducirRes.setText("Añadir resultados");
        introducirRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                introducirResActionPerformed(evt);
            }
        });
        jMenu4.add(introducirRes);

        verRes.setText("Ver resultados");
        verRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verResActionPerformed(evt);
            }
        });
        jMenu4.add(verRes);

        eliminarRes.setText("Borrar resultados");
        eliminarRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarResActionPerformed(evt);
            }
        });
        jMenu4.add(eliminarRes);

        jMenuBar1.add(jMenu4);

        vResultadosTot.setText("BS Championship");

        jMenuItem1.setText("Ver resultados totales");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        vResultadosTot.add(jMenuItem1);

        verEqClas.setText("Ver equipos clasificados a Worlds");
        verEqClas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verEqClasActionPerformed(evt);
            }
        });
        vResultadosTot.add(verEqClas);

        clasfLCQ.setText("Ver equipos clasificados a LCQ");
        clasfLCQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clasfLCQActionPerformed(evt);
            }
        });
        vResultadosTot.add(clasfLCQ);

        mostrarFec.setText("Ver fechas del torneo");
        mostrarFec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarFecActionPerformed(evt);
            }
        });
        vResultadosTot.add(mostrarFec);

        jMenuBar1.add(vResultadosTot);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarEquiposActionPerformed
        equipo.mostrarEquiposRegiones();
    }//GEN-LAST:event_mostrarEquiposActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        JOptionPane.showMessageDialog(null, "¡Hasta la vista!", "Let's Brawl", JOptionPane.INFORMATION_MESSAGE, icono);
        dispose();
    }//GEN-LAST:event_salirActionPerformed

    private void crearEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearEquipoActionPerformed
        equipo.crearEquipo();
    }//GEN-LAST:event_crearEquipoActionPerformed

    private void modificarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarEquipoActionPerformed
        equipo.modificarEquipo();
    }//GEN-LAST:event_modificarEquipoActionPerformed

    private void verResultadosTotalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verResultadosTotalesActionPerformed
        resultados.verResultadosRegiones();
    }//GEN-LAST:event_verResultadosTotalesActionPerformed

    private void eliminarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarEquipoActionPerformed
        equipo.eliminarEquipo();
    }//GEN-LAST:event_eliminarEquipoActionPerformed

    private void mostrarResultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarResultadosActionPerformed
        resultados.mostrarResultados();
    }//GEN-LAST:event_mostrarResultadosActionPerformed

    private void introduceResultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_introduceResultadosActionPerformed
       resultados.introducirResultados();
    }//GEN-LAST:event_introduceResultadosActionPerformed

    private void eliminarResultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarResultadosActionPerformed
        resultados.borrarResultados();
    }//GEN-LAST:event_eliminarResultadosActionPerformed

    private void buscarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarEquipoActionPerformed
        resultados.buscarEquipo(getTextoEquipo());
    }//GEN-LAST:event_buscarEquipoActionPerformed

    private void salirProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirProgramaActionPerformed
        JOptionPane.showMessageDialog(null, "¡Hasta la vista!", "Let's Brawl", JOptionPane.INFORMATION_MESSAGE, icono);
        dispose();
    }//GEN-LAST:event_salirProgramaActionPerformed

    private void crearEqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearEqActionPerformed
        equipo.crearEquipo();
    }//GEN-LAST:event_crearEqActionPerformed

    private void mostrarEqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarEqActionPerformed
        equipo.mostrarEquiposRegiones();
    }//GEN-LAST:event_mostrarEqActionPerformed

    private void modificarEqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarEqActionPerformed
        equipo.modificarEquipo();
    }//GEN-LAST:event_modificarEqActionPerformed

    private void eliminarEqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarEqActionPerformed
        equipo.eliminarEquipo();
    }//GEN-LAST:event_eliminarEqActionPerformed

    private void introducirResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_introducirResActionPerformed
        resultados.introducirResultados();
    }//GEN-LAST:event_introducirResActionPerformed

    private void verResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verResActionPerformed
        resultados.mostrarResultados();
    }//GEN-LAST:event_verResActionPerformed

    private void eliminarResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarResActionPerformed
        resultados.borrarResultados();
    }//GEN-LAST:event_eliminarResActionPerformed

    private void verEqClasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verEqClasActionPerformed
        resultados.verEquiposClasificadosWorlds();
    }//GEN-LAST:event_verEqClasActionPerformed

    private void verFechasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verFechasActionPerformed
        resultados.mostrarFechas();
    }//GEN-LAST:event_verFechasActionPerformed

    private void mostrarFecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarFecActionPerformed
        resultados.mostrarFechas();
    }//GEN-LAST:event_mostrarFecActionPerformed

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        limpiarTabla();
    }//GEN-LAST:event_limpiarActionPerformed

    private void limpiarTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarTabActionPerformed
        limpiarTabla();
    }//GEN-LAST:event_limpiarTabActionPerformed

    private void clasificadosLCQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clasificadosLCQActionPerformed
        resultados.verEquiposClasificadosLCQ();
    }//GEN-LAST:event_clasificadosLCQActionPerformed

    private void clasfLCQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clasfLCQActionPerformed
        resultados.verEquiposClasificadosLCQ();
    }//GEN-LAST:event_clasfLCQActionPerformed

    private void mostrarEquiposClasificadosWorlds1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarEquiposClasificadosWorlds1ActionPerformed
        resultados.verEquiposClasificadosWorlds();
    }//GEN-LAST:event_mostrarEquiposClasificadosWorlds1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        resultados.verResultadosRegiones();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BSC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BSC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BSC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BSC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    
    
    public void limpiarTabla(){
        while(dtm.getRowCount() > 0){
            dtm.removeRow(0);
        }
    }
    
    public static void setTablaFechas(String datos[]){
        String titulosTabla[] = {"Región", "Final Mensual", "Fecha", "Hora"};
        dtm.setColumnIdentifiers(titulosTabla);
        while(dtm.getRowCount() > 0){
            dtm.removeRow(0);
        }
        dtm.addRow(datos);
    }
    
    public static void setTablaBuscador(String datos[], int contadorEq){
        String titulosTabla[] = {"id", "Nombre equipo", "Región", "Puntos"};
        dtm.setColumnIdentifiers(titulosTabla);
        contadorEq = contadorEq - 1;
        while(dtm.getRowCount() > contadorEq){
            dtm.removeRow(0);
        }
        dtm.addRow(datos);
    }
    
    
    public static void setTablaBuscadorAlt(String datos[]){
        String titulosTabla[] = {"id", "Nombre equipo", "Región"};
        dtm.setColumnIdentifiers(titulosTabla);
        while(dtm.getRowCount() > 0){
            dtm.removeRow(0);
        }
        dtm.addRow(datos);
    }
    
    
    public static void setTablaEquipos(String datos[], int region){
        String titulosTabla[] = {"id", "Nombre equipo", "Región"};
        dtm.setColumnIdentifiers(titulosTabla);
        int contadorEquipos = Equipo.contadorEquiposRegion(region);
        contadorEquipos = contadorEquipos - 1;
        while(dtm.getRowCount() > contadorEquipos){
            dtm.removeRow(0);
        }
        dtm.addRow(datos);
    }
    
    
    public static void setTablaEquipoRegiones(String datos[], int region){
        String titulosTabla[] = {"id", "Nombre equipo", "Región", "Puntos"};
        dtm.setColumnIdentifiers(titulosTabla);
        int contadorEquipos = Equipo.contadorEquiposRegion(region);
        contadorEquipos = contadorEquipos - 1;
        while(dtm.getRowCount() > contadorEquipos){
            dtm.removeRow(0);
        }
        dtm.addRow(datos);
    }

    
    public static void setTablaResultados(String datos[], int total){
        String titulosTabla[] = {"id", "Nombre equipo", "Región", "Puntos"};
        dtm.setColumnIdentifiers(titulosTabla);
        while(dtm.getRowCount() > total){
            dtm.removeRow(0);
        }
        dtm.addRow(datos);
    }

    
    public static String getTextoEquipo() {
        String equipo = textoEquipo.getText();
        return equipo;
    }

    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Archivo;
    private javax.swing.JButton buscarEquipo;
    private java.awt.Button button1;
    private javax.swing.JMenuItem clasfLCQ;
    private javax.swing.JToggleButton clasificadosLCQ;
    private javax.swing.JMenuItem crearEq;
    private javax.swing.JButton crearEquipo;
    private javax.swing.JMenuItem eliminarEq;
    private javax.swing.JButton eliminarEquipo;
    private javax.swing.JMenuItem eliminarRes;
    private javax.swing.JButton eliminarResultados;
    private javax.swing.JLabel imagen;
    private javax.swing.JButton introduceResultados;
    private javax.swing.JMenuItem introducirRes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private javax.swing.JToggleButton limpiar;
    private javax.swing.JMenuItem limpiarTab;
    private javax.swing.JMenuItem modificarEq;
    private javax.swing.JButton modificarEquipo;
    private javax.swing.JMenuItem mostrarEq;
    private javax.swing.JButton mostrarEquipos;
    private javax.swing.JButton mostrarEquiposClasificadosWorlds1;
    private javax.swing.JMenuItem mostrarFec;
    private javax.swing.JButton mostrarResultados;
    private javax.swing.JButton salir;
    private javax.swing.JMenuItem salirPrograma;
    private static javax.swing.JTable tabla;
    private static javax.swing.JTextField textoEquipo;
    private javax.swing.JMenu vResultadosTot;
    private javax.swing.JMenuItem verEqClas;
    private javax.swing.JButton verFechas;
    private javax.swing.JMenuItem verRes;
    private javax.swing.JButton verResultadosTotales;
    // End of variables declaration//GEN-END:variables
}
